
export const temas = {
  /*Cores do tema claro*/
  light: {
    background: "#F0F0F0",
    color: "#1A1A24",       
    seatSelected: "#DB3D2E",  
    seatAvailable: "#1A1A24", 
    background: "#F0F0F0", 
    color: "#1A1A24",
    seatSelected: "#DB3D2E",  
    seatAvailable: "#1A1A24",  
    seatUnavailable: "#BABABA",
    seatInexistente: "#F0F0F0",
    seatInexistente: "#F0F0F0",
    corTela: "#333",
    screenBackground: "#BABABA",
    ballFree: "#1A1A24",
    ballSelected: "#DB3D2E",
    ballFree: "#1A1A24",
    ballSelected: "#DB3D2E", 
    ballOccupied: "#1A1A24",
    botaoCompra: "#DB3D2E",
    botaoCompra: "#DB3D2E", 
    botaoCompraTexto: "#F0F0F0",
  },

  /*Cores do tema escuro*/
  dark: {
    background: "#1A1A24",  
    color: "#F0F0F0",       
    seatSelected: "#CD4A3E",   
    seatAvailable: "#F0F0F0", 
    background: "#1A1A24",
    color: "#F0F0F0",
    seatSelected: "#CD4A3E",
    seatAvailable: "#F0F0F0",
    seatUnavailable: "#505050",
    seatInexistente: "#1A1A24", 
    seatInexistente: "#1A1A24",
    corTela: "#F0F0F0",
    screenBackground: "#505050",
    ballFree: "#F0F0F0",
    ballSelected: "#CD4A3E",
    ballFree: "#F0F0F0",
    ballSelected: "#CD4A3E",
    ballOccupied: "#505050",
    botaoCompra: "#CD4A3E", 
    botaoCompra: "#CD4A3E",
    botaoCompraTexto: "#F0F0F0",
  },
};